### ISSUE TITLE
Cannot launch built binary (library not loaded)

### ISSUE THREAD

**Issue by AxelTerizaki** [ColorsWind/FFmpeg-macOS#1]
Hello and thanks for providing a way to get these universal binaries.

I'm running into trouble when trying to install it on my system. I followed the instructions for download and install but once launched, it fails : 

```
dyld[74730]: Library not loaded: '/Users/runner/work/FFmpeg-macOS/FFmpeg-macOS/ffmpeg/install_universal/lib/libavdevice.59.dylib'
  Referenced from: '/Users/karaokemugen/ffmpeg-n5.0.1/bin/ffmpeg'
  Reason: tried: '/Users/runner/work/FFmpeg-macOS/FFmpeg-macOS/ffmpeg/install_universal/lib/libavdevice.59.dylib' (no such file), '/usr/local/lib/libavdevice.59.dylib' (no such file), '/usr/lib/libavdevice.59.dylib' (no such file)
zsh: abort      ./ffmpeg
```

Any idea how to fix this? It looks like it wants its libraries in a different user folder entirely.

**Comment by ColorsWind** [comment]
Hello,
As for macOS, I need to use `install_name_tool` to modify the dynamic library referenced by executable file (*.dylib & executable). It seems that the process for `ffmepg` and `ffprobe` is not executed. I check and fix it. It should work correctly now. Just use the new `install.py` to install.
